# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Callum Flack is…
author:
    twitter: callumflack
description: |
  CALLUM FLACK is a husband, dad, web designer and amateur musicologist. He also runs a digital studio called Patternworks. On here you’ll find working-in-public notes, marginalia, tangents and other things inbetween.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://callumflack.com" # the base hostname & protocol for your site
assetsurl: "/assets/images/"
social:
    instagram: https://instagram.com/callumflack
twitter:
    username: callumflack
google-analytics: UA-43323845-1

# Defaults
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            permalink: "/:categories/:title.html"
            layout: article

# Collections
collections:
    posts:
        title: Posts
        output: true

# Markdown settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

# Sass settings
# sass:
#   add_charset: true
#   sass_dir: assets/sass
#   style: :compressed

# Build settings
exclude:
- Gemfile
- Gemfile.lock
- gulpfile.js
- package.json
- node_modules
- README.md
- TODO.md
- assets/*-subset
- assets/*-src
- assets/icons

# Plugin settings
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
